#!/bin/bash

if [ "$#" -lt 2 ] && [ "$#" -gt 5 ]
 then
    echo Illeagal Arguments
elif [ "$#" -eq 2 ] #Only two args
 then
    java Client $1 $2
elif [ "$#" -eq 3 ]
 then
    java Client $1 $2 $3
elif [ "$#" -eq 4 ]
 then
    java Client $1 $2 $3 $4
else
    java Client $1 $2 $3 $4 $5
fi
