gnuplot pic_builder/exp1_throughput.gnu
gnuplot pic_builder/exp1_droprate.gnu
gnuplot pic_builder/exp1_delay.gnu

gnuplot pic_builder/exp2_Reno_Reno_throughput.gnu
gnuplot pic_builder/exp2_Reno_Reno_droprate.gnu
gnuplot pic_builder/exp2_Reno_Reno_delay.gnu
gnuplot pic_builder/exp2_NewReno_Reno_throughput.gnu
gnuplot pic_builder/exp2_NewReno_Reno_droprate.gnu
gnuplot pic_builder/exp2_NewReno_Reno_delay.gnu
gnuplot pic_builder/exp2_Vegas_Vegas_throughput.gnu
gnuplot pic_builder/exp2_Vegas_Vegas_droprate.gnu
gnuplot pic_builder/exp2_Vegas_Vegas_delay.gnu
gnuplot pic_builder/exp2_NewReno_Vegas_throughput.gnu
gnuplot pic_builder/exp2_NewReno_Vegas_droprate.gnu
gnuplot pic_builder/exp2_NewReno_Vegas_delay.gnu

gnuplot pic_builder/exp3_Sack_delay.gnu
gnuplot pic_builder/exp3_Reno_delay.gnu
gnuplot pic_builder/exp3_Sack_RED_throughput.gnu
gnuplot pic_builder/exp3_Sack_DropTail_throughput.gnu
gnuplot pic_builder/exp3_Reno_DropTail_throughput.gnu
gnuplot pic_builder/exp3_Reno_RED_throughput.gnu

rm *.dat
